# Generated by Django 6.0.4 on 2026-04-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (used if no uploaded image)'),
        ),
    ]
